### ISSUE TITLE
letsencrypt failed to generate certificate

### ISSUE THREAD

**Issue by hdep** [voxpupuli/puppet-letsencrypt#184]
Hi,

I just deployed the module and try to get a certificate. It appears that it never worked. Looking at the logs I see an error : 

```
2019-04-17 14:51:49,562:DEBUG:certbot.storage:Creating directory /etc/letsencrypt/archive.
2019-04-17 14:51:49,562:DEBUG:certbot.storage:Creating directory /etc/letsencrypt/live.
2019-04-17 14:51:49,562:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1225, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    self.config)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 1026, in new_lineage
    cli_config.renewal_configs_dir, lineagename)
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 280, in unique_lineage_name
    return safe_open(preferred_path, chmod=chmod), preferred_path
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 229, in safe_open
    os.open(path, os.O_CREAT | os.O_EXCL | os.O_RDWR, *open_args),
FileNotFoundError: [Errno 2] No such file or directory: '/etc/letsencrypt/renewal/api-partenaires-recette.domain.com/.conf'
2019-04-17 14:51:49,563:ERROR:certbot.log:An unexpected error occurred:
```

Not sure if this error is generated by the module or by letsencrypt. 
Here is my hiera configuration : 

```
letsencrypt::email: 'mail@mail.com'
letsencrypt::certonly:
      'api-partenaires-recette.domain.com':
         domains:
           - 'api-partenaires-recette.domain.com'
         plugin: 'webroot'
         webroot_paths:
           - '/applis/www/api_partenaire/public'
```

The thing is I don't know what is the following file : : '/etc/letsencrypt/renewal/api-partenaires-recette.domain.com/.conf' 

The second issue is that has puppet run every 30 minutes I blocked the domain : 

`
2019-04-17 16:54:09,419:ERROR:certbot.log:There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: api-partenaires-recette.domain.com: see https://letsencrypt.org/docs/rate-limits/`

I don't know if we can do something to prevent this situation.

Any idea ?

**Comment by Dan33l** [comment]
Hi @hdep please paste the puppet code that show how you call the module.

**Comment by hdep** [comment]
Yes sorry, I have created the following profile : 
```

   include letsencrypt
   if lookup( {"name" => 'letsencrypt::certonly', "default_value" => ''} ) != '' {
      create_resources('letsencrypt::certonly', hiera_hash('letsencrypt::certonly'))
   }
```

**Comment by Dan33l** [comment]
The template should asked the following when you created the issue :
    Puppet: Version? All in One provided by Puppet Inc?
    Distribution: ?
    Module version: ?

**Comment by hdep** [comment]
Sorry,
Puppet: AIO puppet 5.5.12-1stretch
Distribution: Debian 9
Module version: 4.0.0

I created another test domain, and it worked so I guess my initial configuration was wrong, I'm not able to reproduce the exact issue.

**Comment by Dan33l** [comment]
So can we consider to close the issue ?

**Comment by hdep** [comment]
If I was able to get locked from letsencrypt I assume there is  something wrong, but yeah lets close this has we don't have any idea.

**Comment by Dan33l** [comment]
You are probably right. But without being able to reproduce it is hard to debug. 
Feel free to reopen in any case.
