### ISSUE TITLE
Recent update causes problems with the nginx plugin

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-letsencrypt#250]
On this host, letsencrypt did work fine with a workaround I had in place, which I lost, so I have to start digging again:
```
2021-09-28 05:32:46,599:DEBUG:certbot.main:certbot version: 0.31.0
2021-09-28 05:32:46,600:DEBUG:certbot.main:Arguments: ['-q']
2021-09-28 05:32:46,602:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-09-28 05:32:46,611:DEBUG:certbot.log:Root logging level set at 30
2021-09-28 05:32:46,611:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-09-28 05:32:46,626:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7fdd938cdd30> and installer <certbot.cli._Default object at 0x7fdd938cdd30>
2021-09-28 05:32:46,626:DEBUG:certbot.cli:Var server=https://acme-v02.api.letsencrypt.org/directory (set by user).
2021-09-28 05:32:46,626:DEBUG:certbot.cli:Var server=https://acme-v02.api.letsencrypt.org/directory (set by user).
2021-09-28 05:32:46,626:DEBUG:certbot.cli:Var account={'server'} (set by user).
2021-09-28 05:32:46,642:INFO:certbot.renewal:Cert not yet due for renewal
2021-09-28 05:32:46,652:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer None
2021-09-28 05:32:46,652:DEBUG:certbot.renewal:no renewal failures
2021-09-28 12:41:02,591:DEBUG:certbot.main:certbot version: 0.31.0
2021-09-28 12:41:02,592:DEBUG:certbot.main:Arguments: ['--keep-until-expiring', '--text', '--agree-tos', '--non-interactive', '--rsa-key-size', '4096', '-a', 'nginx', '--cert-name', 'quigon.example.com', '-d', 'quigon.example.com']
2021-09-28 12:41:02,592:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-09-28 12:41:02,607:DEBUG:certbot.log:Root logging level set at 20
2021-09-28 12:41:02,608:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-09-28 12:41:02,609:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer None
2021-09-28 12:41:02,609:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#nginx): Could not find a usable 'nginx' binary. Ensure nginx exists, the binary is executable, and your PATH is set correctly.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 145, in prepare
    "Could not find a usable 'nginx' binary. Ensure nginx exists, "
certbot.errors.NoInstallationError: Could not find a usable 'nginx' binary. Ensure nginx exists, the binary is executable, and your PATH is set correctly.
2021-09-28 12:41:02,610:DEBUG:certbot.plugins.selection:No candidate plugin
2021-09-28 12:41:02,610:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2021-09-28 12:41:02,610:INFO:certbot.main:Could not choose appropriate plugin: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError("Could not find a usable 'nginx' binary. Ensure nginx exists, the binary is executable, and your PATH is set correctly.",)
2021-09-28 12:41:02,611:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1229, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 237, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 341, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
certbot.errors.PluginSelectionError: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError("Could not find a usable 'nginx' binary. Ensure nginx exists, the binary is executable, and your PATH is set correctly.",)
```

If I do the same from the CLI, it works OK:
```
# /opt/puppetlabs/puppet/cache/letsencrypt/renew-quigon.example.com.sh
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer None
Cert not yet due for renewal
Keeping the existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

So I strongly suspect the path is not properly set in the generated shell script:

Whilst being there: I noticed quite a bit of code repetition:
```
root@theforeman ~/modules/letsencrypt # ag -- "#\!/bin/sh\\\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\\\n"
spec/defines/letsencrypt_certonly_spec.rb
231:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
258:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
272:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
286:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
313:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
327:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
436:        it { is_expected.to contain_file('/var/lib/puppet/letsencrypt/renew-foo.example.com.sh').with_ensure('file').with_content("#!/bin/sh\nletsencrypt --keep-until-expiring --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a standalone --cert-name 'foo.example.com' -d 'foo.example.com'\n") }
```

Perhaps defining this as a variable would be nicer. And adding `/usr/sbin:/usr/local/sbin` to the `PATH` would be practical as well.

**Comment by hboetes** [comment]
Workaround for this problem, set the path like this:

```
  letsencrypt::certonly {$fqdn:
    domains              => [$fqdn],
    plugin               => 'nginx',
    webroot_paths        => ['/var/www/html'],
    manage_cron          => true,
    environment          => ['PATH=/usr/sbin:/usr/bin:/sbin:/bin'],                                                                                    
    cron_success_command => '/bin/systemctl reload nginx.service',
  }
```
